config/routes.rb
Rails.application.routes.draw do
  get 'artists/index'

  get 'artists/show'

  get 'artists/edit'

  get 'artists/new'

  root 'billboards#index'
  resources :billboards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :songs
end

app/models/billboard.rb
class Billboard < ApplicationRecord
    validates :title, presence: true
    has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :billboard
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def new
  end
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :edit, :update, :destroy] 

  def index
    @billboards = Billboard.all
  end

  def show
  end

  def new
    @billboard = Billboard.new
  end

  def create
    @billboard = Billboard.new(billboard_params)
    if @billboard.save
      redirect_to billboards_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @billboard.update(billboard_params)
      redirect_to billboards_path
    else
      render :edit
    end
  end

  def destroy
    @billboard.destroy
    redirect_to billboards_path
  end

  private
    def billboard_params
      params.require(:billboard).permit(:title, :active)
    end

    def set_billboard
      @billboard = Billboard.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h1>Artists#index</h1>
<p>Find me in app/views/artists/index.html.erb</p>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1>Artists#show</h1>
<p>Find me in app/views/artists/show.html.erb</p>

app/views/billboards/edit.html.erb
<h1>Edit Billboard</h1>
<hr />

<%= form_for @billboard do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :active %>
    <%= f.check_box :active %>

    <%= f.submit %>
<% end %>

app/views/billboards/index.html.erb
<h1>All billboards!</h1>

<hr />

<%= link_to 'New Billboard', new_billboard_path%>
<br />

<ul>
    <% @billboards.each do |billboard| %>
        <li><%= link_to billboard.title, billboard_path(billboard.id) %></l1>
    <% end %>
</ul>

app/views/billboards/new.html.erb
<h1>New Billboard</h1>
<hr />

<%= form_for @billboard do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :active %>
    <%= f.check_box :active %>

    <%= f.submit %>
<% end %>

<hr />

<%= link_to 'Cancel', billboards_path %>

app/views/billboards/show.html.erb
<h1><%= @billboard.title %></h1>
<hr />

<%= link_to 'Edit', edit_billboard_path(@billboard.id) %>
<%= link_to 'Delete', billboard_path(@billboard.id), method: :delete %>
<%= link_to 'Home', billboards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BillboardW17</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>